baseURL = 'https://bettzen.com/'
theme = "blowfish"
title = "深圳百陈服装有限公司 | Bettzen"
defaultContentLanguage = "en"
[taxonomies]
  tag = "tags"
  category = "categories"
publishDir = "docs"
[params]
  enableSRI = false
[markup.goldmark.renderer]
  unsafe = true
 [sitemap]
  filename = "sitemap.xml"
enableRobotsTXT = true

[languages.en]
  languageName = "English"
  weight = 1

[languages.zh]
  languageName = "简体中文"
  weight = 2