name: Deploy Hugo Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用您已配置好的个人访问令牌，拥有完全权限
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # 明确指定发布目录，即Hugo构建输出
          publish_dir: ./public
          # 关键：强制指定发布到 `gh-pages` 分支
          publish_branch: gh-pages
          # 保持分支历史干净，这对于用户站点很重要
          force_orphan: true
          # 可选：为提交信息添加自定义消息
          commit_message: ${{ github.event.head_commit.message }}